### ISSUE TITLE
Parameterize control factors in methods 

### ISSUE THREAD

**Issue by cpfaff** [cpfaff/ease#32]

**Comment by cpfaff** [comment]
@EichenbergBEF  We could also take inspiration from the geobon initiative on essential biodiversity variables for our top ten list. What do you think about these. 

http://www.geobon.org/Downloads/articles/2013/201303_ebv_table.pdf

**Comment by EichenbergBEF** [comment]
I think the quite generic structure and naming of these factors is great 
and we should really stick to such a generality in determining the 
control facotrs (top 10 list). This is quite appealing to have very 
general control factor classes.

However, I think this list really lacks some important aspects. I mean 
there is no class allowing to refer to e.g. soil measurements (e.g. pH 
value, granulary usw.).
e.g. "Soil physicochemical parameters" (I know "physicochemical" is more 
than a single concept, but let's take this for now) as a Control 
parameter, which the comprises "soil nutrient status", "pH-value", usw.
these more generic classes can then (where really necessary) be broken 
down into "Soil chemical parameters" (which comprises pH-vale, nuritents 
etc) and "Soil physical parameters (which then may comprise soil 
moisture, soil gtranularity).

The classes within the Control Factors then have to be described in more 
detail in the vocabulary, so that the user knows what has to be 
categorized as what.

In general I find the approach of "being more general" (e.g. Soil 
physicochemical parameters) in the beginning, and then , splitting up 
the classes where necessary (Soil physical & Soil chemical) is quite 
appealing. If you start from very detailed information which you then 
acgglomerate from detailed -> generic, you might easily get lost in the 
details, whereas general -> detail may save you from beig too accurate.

Am 20.01.2016 um 13:42 schrieb Claas-Thido Pfaff:

> @EichenbergBEF https://github.com/EichenbergBEF We could also use 
> the the important variables from the geobon initiative on essential 
> biodiversity variables for out top ten list. What do you think about 
> these.
> 
> http://www.geobon.org/Downloads/articles/2013/201303_ebv_table.pdf
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/cpfaff/cafe/issues/32#issuecomment-173193275.

## 

Dr. rer. nat. David Eichenberg
BEF-China research consortium
Data manager (BEF China Dataportal)
Tel: 0049-341-9738587
Department of Systematic Botany and Functional Biodiversity
University of Leipzig
Room 120
Johannisalles 21
04103 Leipzig GERMANY

**Comment by cpfaff** [comment]
That is a tough one. We have the same problems as we had with processes. What the hack is a control factor. And that is the problem. It is not something that we just measure and that has necessarily a unit. It might be something that we controlled in our setup which could be almost everything. Maybe we need the workshop here later as you @EichenbergBEF  suggested to agree on a best of list and then agree on some sensitive attributes that could be used for a classification. 

For now I will try to merge what we have with what is provide by the ebv document.

**Comment by cpfaff** [comment]
After checking them now in more detail and thinking about it I would say they do not help as much as I was hoping. They are sometimes more or less easy measurables and the other time they represent very hard to grasp complex things (e.g. disturbance regime).

**Comment by cpfaff** [comment]
By that I mean they do not solve the problem we have. They are rather of the same kind like what we already have.
