### ISSUE TITLE
Add soil types from WRB

### ISSUE THREAD

**Issue by cpfaff** [cpfaff/ease#33]
We are currently only using the general classes defined in the WRB for soil types. While this is helpful in general iit does not hurt if we also have more detail in the vocabulary. We had this in the beginning however decided to remove it as we found it to detailed. I do not thing this is a problem as we can keep the general classes as well. So these can be used for annotation or if you know better your can just select the exact soil type.

**Comment by EichenbergBEF** [comment]
While in general I completely agree with you that the possibility to  
go into more detail is favourable without the explicit need to do so  
you should keep in mind the following:

In every situation you allow for either more or less detailed  
annotations, the search algorithm must be able to abstract the  
information from the more detailed level to the more general level or  
vice-versa in order to retrieve certain datasets in a search.

Merry christmas!!

Zitat von Claas-Thido Pfaff notifications@github.com:

**Comment by cpfaff** [comment]
I am adding this now fully. I am currently compiling a document that clarifies the relations between the vocabulary and the schema. The document will help to find out what to preselect and show in the application and what to keep as backup for more detail in the background.

**Comment by cpfaff** [comment]
This is done now in the open office document just checked into the repository [here](https://github.com/cpfaff/cafe/blob/master/assets/documents/SchemaAndVocabulary.odt?raw=true). This will be used to guide the shaping of the thesaurus then.

**Comment by cpfaff** [comment]
This will be an own issue though
